# Generated by Django 3.2.3 on 2021-10-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0002_eventorganizer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventorganizer',
            new_name='Organizer',
        ),
    ]
