# Generated by Django 3.2.7 on 2021-10-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0003_eventform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=200)),
                ('lastname', models.CharField(blank=True, max_length=200)),
                ('sport', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=122)),
                ('phonenumber', models.IntegerField()),
                ('address', models.TextField(blank=True)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
