# Generated by Django 3.2.3 on 2021-10-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0004_auto_20211005_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='organizer',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='organizer',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
