# Generated by Django 3.2.3 on 2021-10-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0005_auto_20211005_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='gender',
        ),
    ]
