# Generated by Django 3.2.3 on 2021-10-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0006_remove_organizer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='gender',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
