# Generated by Django 3.2.3 on 2021-10-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0010_storef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=20)),
                ('number', models.IntegerField()),
                ('local', models.CharField(blank=True, max_length=122)),
            ],
        ),
    ]
