# Generated by Django 3.2.3 on 2021-10-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0011_eventform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventform',
            name='date',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
